HAI 1.2
    I HAS A P ITZ A NUMBR
    I HAS A C ITZ A NUMBR
    GIMMEH P
    P IS NOW A NUMBR
    GIMMEH C
    C IS NOW A NUMBR

    I HAS A score ITZ DIFF OF PRODUKT OF P AN 50 AN PRODUKT OF C AN 10

    BOTH SAEM P AN BIGGR OF P AN C
    O RLY?
        YA RLY
            score R SUM OF score AN 500
    OIC
    VISIBLE score
KTHXBYE